Building DAG of jobs...
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	solve_all_iterations
	3	solve_iterations
	4

[Sat May 29 17:40:15 2021]
rule solve_iterations:
    input: pypsa-eur/networks/elec_s_5_ec_lcopt_Co2L-24H.nc, data/curve.csv, data/costs.csv
    output: iterations/elec_s_5_ec_lcopt_Co2L-24H_0.nc
    log: logs\solve_iterations\elec_s_5_ec_lcopt_Co2L-24H_0_solver.log, logs/solve_iterations/elec_s_5_ec_lcopt_Co2L-24H_0_python.log, logs/solve_iterations/elec_s_5_ec_lcopt_Co2L-24H_0_memory.log
    jobid: 1
    wildcards: iterations=0

Opening notebook for editing.
[Sat May 29 17:47:35 2021]
Error in rule solve_iterations:
    jobid: 1
    output: iterations/elec_s_5_ec_lcopt_Co2L-24H_0.nc
    log: logs\solve_iterations\elec_s_5_ec_lcopt_Co2L-24H_0_solver.log, logs/solve_iterations/elec_s_5_ec_lcopt_Co2L-24H_0_python.log, logs/solve_iterations/elec_s_5_ec_lcopt_Co2L-24H_0_memory.log (check log file(s) for error message)

RuleException:
CalledProcessError in line 43 of C:\Users\pcpar\Desktop\Tesis\New_Attempt\Independent_convergence\Snakefile:
Command 'jupyter notebook --browser ':' --no-browser --log-level ERROR --ip localhost --port 8888 --NotebookApp.quit_button=True "C:\Users\pcpar\Desktop\Tesis\New_Attempt\Independent_convergence\.snakemake\scripts\tmp83l2rv1z.solve_iterations.py.ipynb"' returned non-zero exit status 4294967295.
  File "C:\Users\pcpar\anaconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 2317, in run_wrapper
  File "C:\Users\pcpar\Desktop\Tesis\New_Attempt\Independent_convergence\Snakefile", line 43, in __rule_solve_iterations
  File "C:\Users\pcpar\anaconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 566, in _callback
  File "C:\Users\pcpar\anaconda3\envs\pypsa-eur\lib\concurrent\futures\thread.py", line 57, in run
  File "C:\Users\pcpar\anaconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 552, in cached_or_run
  File "C:\Users\pcpar\anaconda3\envs\pypsa-eur\lib\site-packages\snakemake\executors\__init__.py", line 2348, in run_wrapper
Terminating processes on user request, this might take some time.
Complete log: C:\Users\pcpar\Desktop\Tesis\New_Attempt\Independent_convergence\.snakemake\log\2021-05-29T174014.904767.snakemake.log
